// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactRouterDom from "react-router-dom";
import * as GameLandingPage from "./GameLandingPage";

var Router = {};

var Switch = {};

var Route = {};

var gameLandingPage = GameLandingPage.GameLandingPage;

import classes from "./application.module.css"
;

var applicationClass = classes.application;

function $$default(param) {
  return React.createElement("div", {
              className: applicationClass
            }, React.createElement(ReactRouterDom.BrowserRouter, {
                  children: React.createElement(ReactRouterDom.Switch, {
                        children: null
                      }, React.createElement(ReactRouterDom.Route, {
                            path: "/",
                            component: gameLandingPage
                          }), React.createElement(ReactRouterDom.Route, {
                            path: "/game1",
                            component: gameLandingPage
                          }))
                }));
}

export {
  Router ,
  Switch ,
  Route ,
  gameLandingPage ,
  applicationClass ,
  $$default ,
  $$default as default,
  
}
/* gameLandingPage Not a pure module */
